# Generated by Django 4.1.4 on 2022-12-24 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taker', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid Number', regex='\\\\A[0-9]{10}\\\\z')])),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
            options={
                'verbose_name': 'Issued',
            },
        ),
    ]
