# Generated by Django 4.1.4 on 2022-12-24 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_issued_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid Number', regex='^[0-9]{10}$"')]),
        ),
    ]
