# Generated by Django 4.1.4 on 2022-12-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_issued_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
