# Generated by Django 4.1.4 on 2022-12-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_issued_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
