# Generated by Django 4.1.4 on 2022-12-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued',
            name='date_of_issue',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='issued',
            name='date_of_return',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='issued',
            name='has_returned',
            field=models.BooleanField(default=False),
        ),
    ]
